import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    'fr-FR': {
        staffHubInfeenyTitle: 'Infeeny - Sud-Est',
        staffHubPlanner: 'Planning',
        staffHubParameter: 'Paramètres',
        staffHubToday: 'Aujourd\'hui',
        staffHubJanuary: 'Janvier',
        staffHubFebruary: 'Février',
        staffHubMarch: 'Mars',
        staffHubApril: 'Avril',
        staffHubMay: 'Mai',
        staffHubJune: 'Juin',
        staffHubJuly: 'Juillet',
        staffHubAugust: 'Août',
        staffHubSeptember: 'Septembre',
        staffHubOctober: 'Octobre',
        staffHubNovember: 'Novembre',
        staffHubDecember: 'Décembre',
        staffHubDays: 'Jour',
        staffHubWeeks: 'Semaine',
        staffHubMonth: 'Mois',
        staffHubError: 'Une erreur est survenue, contacter voter administrateur',
        staffHubLeftPanelTitle: 'Membres',
        staffHubLeftPanelTitleMonth: 'Mois',
        staffHubLeftPanelMemberHour: 'Heure',        
        staffHubNewFormTitle: 'Ajouter un nouveau rendez-vous',
        staffHubNewFormInputTitle: 'Titre',
        staffHubNewFormStartDatePicker: 'Date de début',
        staffHubNewFormEndtDatePicker: 'Date de fin',
        staffHubNewFormStartDatePickerTitle: 'Sélectionner une date de début',
        staffHubNewFormEndDatePickerTitle: 'Sélectionner une date de fin',
        staffHubNewFormChkAllDayEventTitle: 'Journée entière',
        staffHubNewFormCbBoxClient: 'Client',
        staffHubNewFormDdlMembers: 'Membres',
        staffHubNewFormClientPicker: 'Suggestion de client',
        staffHubNewFormClientPickerNotFound: 'Client introuvable',
        staffHubNewFormColor: 'Couleur',
        staffHubNewFormBtnSave: 'Sauvegarder',
        staffHubNewFormBtnEdit: 'Modifier',
        staffHubNewFormBtnDelete: 'Supprimer',
        staffHubNewFormBtnNew: 'Nouveau',
        staffHubNewFormSaveWarningMissingProps: 'Vous devez remplir tous les champs obligatoire avant de valider le formulaire',
        staffHubNewFormSaveWarningErrorDate: 'La date de début ne doit pas être supérieur à la date de fin',
    }
});

export default strings;
