import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    'fr-FR': {
        staffHubInfeenyTitle: 'Infeeny - Sud-Est',
        staffHubPlanner: 'Planning',
        staffHubParameter: 'Paramètres',
        staffHubToday: 'Aujourd\'hui',
        staffHubJanuary: 'Janvier',
        staffHubFebruary: 'Février',
        staffHubMarch: 'Mars',
        staffHubApril: 'Avril',
        staffHubMay: 'Mai',
        staffHubJune: 'Juin',
        staffHubJuly: 'Juillet',
        staffHubAugust: 'Août',
        staffHubSeptember: 'Septembre',
        staffHubOctober: 'Octobre',
        staffHubNovember: 'Novembre',
        staffHubDecember: 'Décembre',
        staffHubDays: 'Jour',
        staffHubWeeks: 'Semaine',
        staffHubMonth: 'Mois',
        staffHubError: 'Une erreur est survenue, contacter voter administrateur',
        staffHubLeftPanelTitle: 'Membres',
        staffHubLeftPanelTitleMonth: 'Mois',
        staffHubNewFormTitle: 'Ajouter un nouveau rendez-vous',
        staffHubNewFormInputTitle: 'Titre',
        staffHubNewFormStartDatePickerTitle: 'Sélectionner une date de début',
        staffHubNewFormEndDatePickerTitle: 'Sélectionner une date de fin',
        staffHubNewFormDdlMembers: 'Membres',
        staffHubNewFormCategoryDdl: 'Sélectionner un type',
        staffHubNewFormCategoryPicker: 'Suggestion de client',
        staffHubNewFormCategoryPickerNotFound: 'Client introuvable',
        staffHubNewFormColor: 'Couleur',
        staffHubNewFormBtnSave: 'Sauvegarder',
        staffHubNewFormBtnEdit: 'Modifier',
        staffHubNewFormBtnDelete: 'Supprimer',
        staffHubNewFormBtnNew: 'Nouveau',
        staffHubNewFormSaveWarningMissingProps: 'Vous devez remplir tous les champs obligatoire avant de valider le formulaire',
        staffHubNewFormSaveWarningErrorDate: 'La date de début ne doit pas être supérieur à la date de fin',
        staffHubParametersTitle: 'Titre',
        staffHubParametersColor: 'Couleur',
        staffHubParametersCategory: 'Clients',
        staffHubParametersDeleteCategory: 'Suppression de la catégorie \'{0}\'',
        staffHubParametersDeleteCategoryMsg: 'La suppression de la catégorie, supprimera toute les tâches associées',
        staffHubParametersDeleteCategoryDelete: 'Supprimer',
        staffHubParametersDeleteCategoryNo: 'Non',
        staffHubParametersMembers: 'Membres',
        staffHubParametersName: 'Nom',
        staffHubParametersEmail: 'Emails',
        staffHubParametersBtnSave: 'Sauvegarder',
        staffHubParametersEditFormTitle: 'Modifier \'{0}\'',
        staffHubParametersAddFormTitle: 'Ajouter'
    }
});

export default strings;
